[shell]
program = "C:/Users/Garrick/AppData/Local/Microsoft/WindowsApps/Microsoft.PowerShell_8wekyb3d8bbwe/pwsh.exe"

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[font]
size = 12.0

[font.normal]
family = "Consolas NF"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9
blur = true

[window.padding]
x = 6
y = 0

#[window.dimensions]
#columns = 90
#lines = 25

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"


# working_directory = "D:/garrickedd/project"